version: '2'
services:
  gjisho-app:
    image: gjisho
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gjisho-postgresql:5432/gjisho
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  gjisho-postgresql:
    extends:
      file: postgresql.yml
      service: gjisho-postgresql
